/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModuleForm.java
 *
 * Created on 28-Feb-2013, 15:09:53
 */

package forms;
import application.Subjects;
import application.Conn;
import javax.swing.DefaultListModel;
import java.util.ArrayList;

/**
 *
 * @author Evilguy
 */
public class ModuleForm extends javax.swing.JInternalFrame {
    private Conn newConnection = new Conn();
    DefaultListModel lstBox = new DefaultListModel();
    ArrayList<Subjects> subjectList = new ArrayList<Subjects>();
    /** Creates new form ModuleForm */
    public ModuleForm() {
        initComponents();
    }


    private void eraseInfo(boolean close){
                txtSubjectID.setText("");
                txtModuleName.setText("");
                txtDesc.setText("");

                if (close){
                    lstBox.removeAllElements();
                }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSubjectID = new javax.swing.JTextField();
        txtModuleName = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        lblSubjectID = new javax.swing.JLabel();
        lblSubjectName = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPersons = new javax.swing.JList(lstBox);
        btnNew = new javax.swing.JButton();
        btnSaveNew = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        txtSubjectID.setEnabled(false);
        getContentPane().add(txtSubjectID);
        txtSubjectID.setBounds(90, 60, 80, 20);
        getContentPane().add(txtModuleName);
        txtModuleName.setBounds(90, 90, 400, 20);
        getContentPane().add(txtDesc);
        txtDesc.setBounds(90, 120, 400, 20);

        lblSubjectID.setText("Module ID:");
        lblSubjectID.setMaximumSize(new java.awt.Dimension(30, 50));
        lblSubjectID.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblSubjectID);
        lblSubjectID.setBounds(10, 60, 80, 20);

        lblSubjectName.setText("Module name:");
        lblSubjectName.setMaximumSize(new java.awt.Dimension(30, 50));
        lblSubjectName.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblSubjectName);
        lblSubjectName.setBounds(10, 90, 80, 20);

        lblDesc.setText("Description:");
        lblDesc.setMaximumSize(new java.awt.Dimension(30, 50));
        lblDesc.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblDesc);
        lblDesc.setBounds(10, 120, 80, 20);

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/floppy-icon.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(110, 490, 100, 40);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close-icon.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(470, 0, 30, 30);

        lstPersons.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPersons.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPersonsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPersons);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 160, 270, 370);

        btnNew.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-file-icon.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew);
        btnNew.setBounds(10, 490, 100, 40);

        btnSaveNew.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnSaveNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/floppy-icon.png"))); // NOI18N
        btnSaveNew.setText("Save New");
        btnSaveNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveNew);
        btnSaveNew.setBounds(10, 490, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // getting modules list from database
        subjectList = newConnection.getSubjectList(STARTME.TESTING);

        lstBox.removeAllElements();
        for (int i=0; i < subjectList.size(); i++){
            lstBox.addElement(""+subjectList.get(i).getSubjectName());
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // updating fields in database
     
        if (!(txtSubjectID.getText().isEmpty()) &&
                         !(txtModuleName.getText().isEmpty()) &&
                         !(txtDesc.getText().isEmpty()))
                         {



                subjectList.get(lstPersons.getSelectedIndex()).setSubjectName(txtModuleName.getText());
                subjectList.get(lstPersons.getSelectedIndex()).setSubjectDescription(txtDesc.getText());

                newConnection.saveSubject(subjectList.get(lstPersons.getSelectedIndex()), STARTME.TESTING);

                this.setVisible(false);
                eraseInfo(true);
        }
      
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
            // close button
                this.setVisible(false);
                eraseInfo(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void lstPersonsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPersonsValueChanged
        // updating screen informaiton about modules
        if (!(lstPersons.isSelectionEmpty())){
            txtSubjectID.setText("" + subjectList.get(lstPersons.getSelectedIndex()).getSubjectID());
            txtModuleName.setText("" + subjectList.get(lstPersons.getSelectedIndex()).getSubjectName());
            txtDesc.setText("" + subjectList.get(lstPersons.getSelectedIndex()).getSubjectDescription());
        }
    }//GEN-LAST:event_lstPersonsValueChanged

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // disable several buttons and selections
        eraseInfo(false);
        btnSave.setEnabled(false);
        btnClose.setEnabled(false);
        lstPersons.setEnabled(false);
        btnSaveNew.setVisible(true);
        btnNew.setVisible(false);


    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNewActionPerformed
    //insert new module into database
        if (!(txtModuleName.getText().isEmpty()) &&
                !(txtDesc.getText().isEmpty())){

                subjectList.add(new Subjects());

                subjectList.get(subjectList.size()-1).setSubjectName(txtModuleName.getText());
                subjectList.get(subjectList.size()-1).setSubjectDescription(txtDesc.getText());

                lstBox.addElement(subjectList.get(subjectList.size()-1).getSubjectName());

                newConnection.insertNewSubject(subjectList.get(subjectList.size()-1), STARTME.TESTING);

                btnSave.setEnabled(true);
                btnClose.setEnabled(true);
                lstPersons.setEnabled(true);
                btnSaveNew.setVisible(false);
                btnNew.setVisible(true);
        }
    }//GEN-LAST:event_btnSaveNewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveNew;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblSubjectID;
    private javax.swing.JLabel lblSubjectName;
    private javax.swing.JList lstPersons;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtModuleName;
    private javax.swing.JTextField txtSubjectID;
    // End of variables declaration//GEN-END:variables

}
