/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PersonalDetails.java
 *
 * Created on 28-Feb-2013, 15:09:53
 */

package forms;
import application.Tutor;
import application.Conn;
import validation.*;
/**
 *
 * @author Evilguy
 */
public class PersonalDetails extends javax.swing.JInternalFrame {
    private Tutor userTMP = new Tutor();
    private Conn newConnection = new Conn();
    //private static final boolean TESTING = true;
    /** Creates new form PersonalDetails */
    public PersonalDetails() {
        initComponents();
    }

    private void eraseInfo(){
         //method that cleans boxes in this form
                txtID.setText("");
                txtPPS.setText("");
                txtName.setText("");
                txtSurname.setText("");
                txtAddress.setText("");
                txtCity.setText("");
                txtPhone.setText("");
                txtDOB.setText("");
                txtEmail.setText("");
                txtLogin.setText("");
                txtPass.setText("");

                cbAdmin.setSelectedIndex(0);
                cbGender.setSelectedIndex(0);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID = new javax.swing.JTextField();
        txtPPS = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblPPS = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        cbAdmin = new javax.swing.JComboBox();
        cbGender = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        txtID.setEnabled(false);
        getContentPane().add(txtID);
        txtID.setBounds(70, 100, 80, 20);

        txtPPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPPSKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPPSKeyTyped(evt);
            }
        });
        getContentPane().add(txtPPS);
        txtPPS.setBounds(270, 100, 120, 20);

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(70, 130, 120, 20);

        txtSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSurnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSurnameKeyTyped(evt);
            }
        });
        getContentPane().add(txtSurname);
        txtSurname.setBounds(270, 130, 120, 20);
        getContentPane().add(txtAddress);
        txtAddress.setBounds(70, 160, 320, 20);
        getContentPane().add(txtCity);
        txtCity.setBounds(70, 190, 120, 20);

        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });
        getContentPane().add(txtPhone);
        txtPhone.setBounds(270, 190, 120, 20);

        txtDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDOBKeyTyped(evt);
            }
        });
        getContentPane().add(txtDOB);
        txtDOB.setBounds(270, 220, 120, 20);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(70, 310, 140, 20);
        getContentPane().add(txtLogin);
        txtLogin.setBounds(70, 250, 140, 20);

        lblID.setText("ID:");
        lblID.setMaximumSize(new java.awt.Dimension(30, 50));
        lblID.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblID);
        lblID.setBounds(10, 100, 60, 20);

        lblPPS.setText("PPS:");
        lblPPS.setMaximumSize(new java.awt.Dimension(30, 50));
        lblPPS.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblPPS);
        lblPPS.setBounds(210, 100, 60, 20);

        lblName.setText("Name:");
        lblName.setMaximumSize(new java.awt.Dimension(30, 50));
        lblName.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblName);
        lblName.setBounds(10, 130, 60, 20);

        lblSurname.setText("Surname:");
        lblSurname.setMaximumSize(new java.awt.Dimension(30, 50));
        lblSurname.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblSurname);
        lblSurname.setBounds(210, 130, 60, 20);

        lblAddress.setText("Address:");
        lblAddress.setMaximumSize(new java.awt.Dimension(30, 50));
        lblAddress.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblAddress);
        lblAddress.setBounds(10, 160, 60, 20);

        lblCity.setText("City:");
        lblCity.setMaximumSize(new java.awt.Dimension(30, 50));
        lblCity.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblCity);
        lblCity.setBounds(10, 190, 60, 20);

        lblPhone.setText("Phone:");
        lblPhone.setMaximumSize(new java.awt.Dimension(30, 50));
        lblPhone.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblPhone);
        lblPhone.setBounds(210, 190, 60, 20);

        lblDOB.setText("Date of birth:");
        lblDOB.setMaximumSize(new java.awt.Dimension(30, 50));
        lblDOB.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblDOB);
        lblDOB.setBounds(190, 220, 80, 20);

        lblGender.setText("Gender:");
        lblGender.setMaximumSize(new java.awt.Dimension(30, 50));
        lblGender.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblGender);
        lblGender.setBounds(10, 220, 60, 20);

        lblEmail.setText("Email:");
        lblEmail.setMaximumSize(new java.awt.Dimension(30, 50));
        lblEmail.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblEmail);
        lblEmail.setBounds(10, 310, 60, 20);

        lblLogin.setText("Login:");
        lblLogin.setMaximumSize(new java.awt.Dimension(30, 50));
        lblLogin.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblLogin);
        lblLogin.setBounds(10, 250, 60, 20);

        lblPass.setText("Password:");
        lblPass.setMaximumSize(new java.awt.Dimension(30, 50));
        lblPass.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblPass);
        lblPass.setBounds(10, 280, 60, 20);

        lblAdmin.setText("Admin:");
        lblAdmin.setMaximumSize(new java.awt.Dimension(30, 50));
        lblAdmin.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblAdmin);
        lblAdmin.setBounds(230, 250, 40, 20);
        getContentPane().add(txtPass);
        txtPass.setBounds(70, 280, 140, 20);

        cbAdmin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "True", "False" }));
        getContentPane().add(cbAdmin);
        cbAdmin.setBounds(270, 250, 120, 20);

        cbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        getContentPane().add(cbGender);
        cbGender.setBounds(70, 220, 80, 20);

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/floppy-icon.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(10, 490, 100, 40);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close-icon.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(470, 0, 30, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // using temporaru user setting information about teacher
        STARTME.tmpUser = STARTME.glUser;
        userTMP = STARTME.tmpUser;
        
        
        txtID.setText(""+userTMP.getbdId());
        txtPPS.setText(userTMP.getPPSNumber());
        txtName.setText(userTMP.getFirstName());
        txtSurname.setText(userTMP.getLastName());
        txtAddress.setText(userTMP.getAddress());
        txtCity.setText(userTMP.getCity());
        txtPhone.setText(userTMP.getPhone());
        txtDOB.setText(userTMP.getDoB());

        txtEmail.setText(userTMP.getEmail());
        txtLogin.setText(userTMP.getLogin());
        txtPass.setText(userTMP.getPassword());
        if (userTMP.getAdmin()){
            cbAdmin.setSelectedIndex(0);
            cbAdmin.setEnabled(true);
        } else {
            cbAdmin.setSelectedIndex(1);
            cbAdmin.setEnabled(false);
        }
        if (userTMP.getGender()){
            cbGender.setSelectedIndex(0);
        } else {
            cbGender.setSelectedIndex(1);
        }


    }//GEN-LAST:event_formInternalFrameActivated

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // updating information about teacher
        userTMP.setdbID(txtID.getText());
        userTMP.setPPSNumber(txtPPS.getText());
        userTMP.setFirstName(txtName.getText());
        userTMP.setLastName(txtSurname.getText());
        userTMP.setAddress(txtAddress.getText());
        userTMP.setCity(txtCity.getText());
        userTMP.setPhone(txtPhone.getText());
        userTMP.setDateOfBirth(txtDOB.getText());
        userTMP.setEmail(txtEmail.getText());
        userTMP.setLogin(txtLogin.getText());
        userTMP.setPassword(txtPass.getText());
        userTMP.setAdmin(cbAdmin.getSelectedItem().toString());
        //set gender
        if (cbGender.getSelectedIndex() == 0){
        userTMP.setGender("true");
        } else {userTMP.setGender("false");}
        newConnection.saveUser(userTMP, userTMP.getbdId());

                eraseInfo();
                this.setVisible(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        //close button
                eraseInfo();
                this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtPPSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPPSKeyTyped
        // TODO add your handling code here:
        datavalidation.ppsValidation(evt,txtPPS);
    }//GEN-LAST:event_txtPPSKeyTyped

    private void txtPPSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPPSKeyReleased
        // TODO add your handling code here:
        autocorrection.ppsCorrection(txtPPS);
    }//GEN-LAST:event_txtPPSKeyReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        autocorrection.nameCorrection(txtName);
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtSurnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurnameKeyReleased
        // TODO add your handling code here:
        autocorrection.nameCorrection(txtSurname);
    }//GEN-LAST:event_txtSurnameKeyReleased

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        // TODO add your handling code here:
        datavalidation.nameValidation(evt);
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtSurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurnameKeyTyped
        // TODO add your handling code here:
        datavalidation.nameValidation(evt);
    }//GEN-LAST:event_txtSurnameKeyTyped

    private void txtDOBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOBKeyTyped
        // TODO add your handling code here:
        datavalidation.dateStandardValidation(evt, txtDOB);
    }//GEN-LAST:event_txtDOBKeyTyped

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        // TODO add your handling code here:
        datavalidation.phoneValidation(evt, txtPhone);
    }//GEN-LAST:event_txtPhoneKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbAdmin;
    private javax.swing.JComboBox cbGender;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPPS;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPPS;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables

}
