/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentToGroup.java
 *
 * Created on 28-Feb-2013, 14:09:53
 */

package forms;
import application.Person;
import application.Group;
import application.Conn;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import validation.*;

/**
 *
 * @author Evilguy
 */
public class StudentToGroup extends javax.swing.JInternalFrame {
    private Conn newConnection = new Conn();
    DefaultListModel lstBox = new DefaultListModel();

    ArrayList<Group> groupList = new ArrayList<Group>();
    ArrayList<Group> groupListAll = new ArrayList<Group>();
    Person student = new Person();
    /** Creates new form StudentToGroup */
    public StudentToGroup() {
        initComponents();
    }


    private void eraseInfo(boolean listBox){
             //method that cleans boxes in this form
                txtID.setText("");
                txtPPS.setText("");
                txtName.setText("");
                txtSurname.setText("");
                txtAddress.setText("");
                txtCity.setText("");
                txtPhone.setText("");
                txtDOB.setText("");
               
                txtPPSNumber.setText("");
                cbGender.setSelectedIndex(0);

                if (listBox){
                    lstBox.removeAllElements();
                }
              
                
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID = new javax.swing.JTextField();
        txtPPS = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblPPS = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox();
        btnRemove = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPersons = new javax.swing.JList(lstBox);
        btnNew = new javax.swing.JButton();
        btnSaveNew = new javax.swing.JButton();
        btnSelectGroup = new javax.swing.JButton();
        txtPPSNumber = new javax.swing.JTextField();
        lblPPS1 = new javax.swing.JLabel();
        cbGroups = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        txtID.setEnabled(false);
        getContentPane().add(txtID);
        txtID.setBounds(70, 100, 80, 20);

        txtPPS.setEnabled(false);
        getContentPane().add(txtPPS);
        txtPPS.setBounds(270, 100, 120, 20);

        txtName.setEnabled(false);
        getContentPane().add(txtName);
        txtName.setBounds(70, 130, 120, 20);

        txtSurname.setEnabled(false);
        getContentPane().add(txtSurname);
        txtSurname.setBounds(270, 130, 120, 20);

        txtAddress.setEnabled(false);
        getContentPane().add(txtAddress);
        txtAddress.setBounds(70, 160, 320, 20);

        txtCity.setEnabled(false);
        getContentPane().add(txtCity);
        txtCity.setBounds(70, 190, 120, 20);

        txtPhone.setEnabled(false);
        getContentPane().add(txtPhone);
        txtPhone.setBounds(270, 190, 120, 20);

        txtDOB.setEnabled(false);
        getContentPane().add(txtDOB);
        txtDOB.setBounds(270, 220, 120, 20);

        lblID.setText("ID:");
        lblID.setMaximumSize(new java.awt.Dimension(30, 50));
        lblID.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblID);
        lblID.setBounds(10, 100, 60, 20);

        lblPPS.setText("PPS:");
        lblPPS.setMaximumSize(new java.awt.Dimension(30, 50));
        lblPPS.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblPPS);
        lblPPS.setBounds(210, 60, 60, 20);

        lblName.setText("Name:");
        lblName.setMaximumSize(new java.awt.Dimension(30, 50));
        lblName.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblName);
        lblName.setBounds(10, 130, 60, 20);

        lblSurname.setText("Surname:");
        lblSurname.setMaximumSize(new java.awt.Dimension(30, 50));
        lblSurname.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblSurname);
        lblSurname.setBounds(210, 130, 60, 20);

        lblAddress.setText("Address:");
        lblAddress.setMaximumSize(new java.awt.Dimension(30, 50));
        lblAddress.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblAddress);
        lblAddress.setBounds(10, 160, 60, 20);

        lblCity.setText("City:");
        lblCity.setMaximumSize(new java.awt.Dimension(30, 50));
        lblCity.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblCity);
        lblCity.setBounds(10, 190, 60, 20);

        lblPhone.setText("Phone:");
        lblPhone.setMaximumSize(new java.awt.Dimension(30, 50));
        lblPhone.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblPhone);
        lblPhone.setBounds(210, 190, 60, 20);

        lblDOB.setText("Date of birth:");
        lblDOB.setMaximumSize(new java.awt.Dimension(30, 50));
        lblDOB.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblDOB);
        lblDOB.setBounds(190, 220, 80, 20);

        lblGender.setText("Gender:");
        lblGender.setMaximumSize(new java.awt.Dimension(30, 50));
        lblGender.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblGender);
        lblGender.setBounds(10, 220, 60, 20);

        cbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        cbGender.setEnabled(false);
        getContentPane().add(cbGender);
        cbGender.setBounds(70, 220, 70, 20);

        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete-file-icon.png"))); // NOI18N
        btnRemove.setText("Del");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove);
        btnRemove.setBounds(110, 490, 100, 40);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close-icon.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(470, 0, 30, 30);

        lstPersons.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstPersons);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 280, 270, 250);

        btnNew.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-file-icon.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew);
        btnNew.setBounds(10, 490, 100, 40);

        btnSaveNew.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnSaveNew.setText("Save New");
        btnSaveNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveNew);
        btnSaveNew.setBounds(10, 490, 100, 40);

        btnSelectGroup.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnSelectGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/file-search-icon.png"))); // NOI18N
        btnSelectGroup.setText("Search");
        btnSelectGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectGroupActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectGroup);
        btnSelectGroup.setBounds(390, 50, 110, 40);

        txtPPSNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPPSNumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPPSNumberKeyTyped(evt);
            }
        });
        getContentPane().add(txtPPSNumber);
        txtPPSNumber.setBounds(270, 60, 120, 20);

        lblPPS1.setText("PPS:");
        lblPPS1.setMaximumSize(new java.awt.Dimension(30, 50));
        lblPPS1.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblPPS1);
        lblPPS1.setBounds(210, 100, 60, 20);

        getContentPane().add(cbGroups);
        cbGroups.setBounds(70, 250, 320, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // clears combo box by the loading time
        cbGroups.setVisible(false);
        cbGroups.removeAllItems();

    }//GEN-LAST:event_formInternalFrameActivated

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
    //removes a field from student group table
        newConnection.removeStudentFromGroup(groupList.get(lstPersons.getSelectedIndex()), student, STARTME.TESTING);

        groupList = newConnection.getStudentGroupList(student, STARTME.TESTING);
        lstBox.removeAllElements();
            for (int i=0; i< groupList.size(); i++){
                lstBox.addElement("" +groupList.get(i).getYear() +" " + groupList.get(i).getCourseName());
            }
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        

                this.setVisible(false);
                eraseInfo(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // disables several buttons and selections
        
        btnRemove.setEnabled(false);
        btnClose.setEnabled(false);
        lstPersons.setEnabled(false);
        btnSaveNew.setVisible(true);
        btnNew.setVisible(false);
        groupListAll = newConnection.getGroupList(STARTME.TESTING);
        cbGroups.removeAllItems();

        //* *** Checking for availability of new group
        for (int x =0; x<groupListAll.size(); x++){
            for (int y=0; y<groupList.size(); y++){
                if (groupListAll.get(x).getGroupID() == groupList.get(y).getGroupID()){
                    groupListAll.remove(x);
                    
                }
            }
        }

        
        //****


        for (int i=0; i<groupListAll.size();i++){
            cbGroups.addItem("" + groupListAll.get(i).getYear() + " " + groupListAll.get(i).getCourseName());
        }

        cbGroups.setVisible(true);



    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNewActionPerformed
    // inserting a field into group student table
        cbGroups.setVisible(false);

        newConnection.insertStudentIntoGroup(groupListAll.get(cbGroups.getSelectedIndex()), student, STARTME.TESTING);

        groupList = newConnection.getStudentGroupList(student, STARTME.TESTING);

        lstBox.removeAllElements();
            for (int i=0; i< groupList.size(); i++){
                lstBox.addElement("" +groupList.get(i).getYear() +" " + groupList.get(i).getCourseName());
            }

        btnRemove.setEnabled(true);
        btnClose.setEnabled(true);
        lstPersons.setEnabled(true);
        btnSaveNew.setVisible(false);
        btnNew.setVisible(true);
        
    }//GEN-LAST:event_btnSaveNewActionPerformed

    private void btnSelectGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectGroupActionPerformed
        // getting a student information and information about all his courses

        student = new Person();

        student.setPPSNumber(txtPPSNumber.getText());

        student = newConnection.getStudent(student, STARTME.TESTING);

        if (student.getbdId()>0){
            txtID.setText(""+student.getbdId());
            txtPPS.setText(student.getPPSNumber());
            txtName.setText(student.getFirstName());
            txtSurname.setText(student.getLastName());
            txtAddress.setText(student.getAddress());
            txtCity.setText(student.getCity());
            txtDOB.setText(student.getDoB());
            txtPhone.setText(student.getPhone());
            


            if (student.getGender()){
                cbGender.setSelectedIndex(0);
            } else {
                cbGender.setSelectedIndex(1);
            }

            groupList = newConnection.getStudentGroupList(student, STARTME.TESTING);

            lstBox.removeAllElements();
            for (int i=0; i< groupList.size(); i++){
                lstBox.addElement("" +groupList.get(i).getYear() +" " + groupList.get(i).getCourseName());
            }


        }


    }//GEN-LAST:event_btnSelectGroupActionPerformed

    private void txtPPSNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPPSNumberKeyReleased
        // autocorrection
        autocorrection.ppsCorrection(txtPPSNumber);
    }//GEN-LAST:event_txtPPSNumberKeyReleased

    private void txtPPSNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPPSNumberKeyTyped
        // validation
        datavalidation.ppsValidation(evt, txtPPSNumber);
    }//GEN-LAST:event_txtPPSNumberKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSaveNew;
    private javax.swing.JButton btnSelectGroup;
    private javax.swing.JComboBox cbGender;
    private javax.swing.JComboBox cbGroups;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPPS;
    private javax.swing.JLabel lblPPS1;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JList lstPersons;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPPS;
    private javax.swing.JTextField txtPPSNumber;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables

}
