/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentResults.java
 *
 * Created on 28-Feb-2013, 15:09:53
 */

package forms;
import application.Person;
import application.Group;
import application.Subjects;
import application.ExamResult;
import application.Exam;
import application.Conn;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import validation.*;

/**
 *
 * @author Evilguy
 */
public class StudentResults extends javax.swing.JInternalFrame {
    private Conn newConnection = new Conn();
    DefaultListModel lstBox = new DefaultListModel();

    ArrayList<Group> groupList = new ArrayList<Group>();
    ArrayList<Person> studentList = new ArrayList<Person>();
    ArrayList<Subjects> subjectList = new ArrayList<Subjects>();
    ArrayList<Exam> examList = new ArrayList<Exam>();
    ExamResult examResult = new ExamResult();

    /** Creates new form StudentResults */
    public StudentResults() {
        initComponents();
    }


    private void eraseInfo(boolean cbBox,boolean listBox){
             //method that cleans boxes in this form
                txtStudentID.setText("");
                txtExamID.setText("");
                txtExamResult.setText("");

                if (listBox){
                    lstBox.removeAllElements();
                }
                //lstPersons.clearSelection();
                if (cbBox){
                    cbGroup.removeAllItems();
                }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStudentID = new javax.swing.JTextField();
        txtExamID = new javax.swing.JTextField();
        txtExamResult = new javax.swing.JTextField();
        lblStudentID = new javax.swing.JLabel();
        lblExamID = new javax.swing.JLabel();
        lblExamResult = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPersons = new javax.swing.JList(lstBox);
        btnNew = new javax.swing.JButton();
        btnSaveNew = new javax.swing.JButton();
        cbGroup = new javax.swing.JComboBox();
        btnSelectGroup = new javax.swing.JButton();
        cbExam = new javax.swing.JComboBox();
        btnSelectSubject = new javax.swing.JButton();
        cbSubject = new javax.swing.JComboBox();
        lblStudentID1 = new javax.swing.JLabel();
        lblStudentID2 = new javax.swing.JLabel();
        lblStudentID3 = new javax.swing.JLabel();
        btnSelectExam = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        txtStudentID.setEnabled(false);
        getContentPane().add(txtStudentID);
        txtStudentID.setBounds(90, 310, 120, 20);

        txtExamID.setEnabled(false);
        getContentPane().add(txtExamID);
        txtExamID.setBounds(90, 340, 120, 20);

        txtExamResult.setEnabled(false);
        txtExamResult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtExamResultKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExamResultKeyTyped(evt);
            }
        });
        getContentPane().add(txtExamResult);
        txtExamResult.setBounds(90, 370, 120, 20);

        lblStudentID.setText("Exam:");
        lblStudentID.setMaximumSize(new java.awt.Dimension(30, 50));
        lblStudentID.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblStudentID);
        lblStudentID.setBounds(10, 160, 60, 20);

        lblExamID.setText("Exam ID:");
        lblExamID.setMaximumSize(new java.awt.Dimension(30, 50));
        lblExamID.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblExamID);
        lblExamID.setBounds(10, 340, 80, 20);

        lblExamResult.setText("Exam Result:");
        lblExamResult.setMaximumSize(new java.awt.Dimension(30, 50));
        lblExamResult.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblExamResult);
        lblExamResult.setBounds(10, 370, 80, 20);

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/floppy-icon.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(110, 490, 100, 40);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close-icon.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(470, 0, 30, 30);

        lstPersons.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPersons.setEnabled(false);
        lstPersons.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPersonsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPersons);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 210, 270, 320);

        btnNew.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-file-icon.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.setEnabled(false);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew);
        btnNew.setBounds(10, 490, 100, 40);

        btnSaveNew.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnSaveNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/floppy-icon.png"))); // NOI18N
        btnSaveNew.setText("Save New");
        btnSaveNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveNew);
        btnSaveNew.setBounds(10, 490, 100, 40);

        cbGroup.setFont(new java.awt.Font("Tahoma", 0, 10));
        getContentPane().add(cbGroup);
        cbGroup.setBounds(70, 60, 320, 20);

        btnSelectGroup.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnSelectGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hd-search-icon.png"))); // NOI18N
        btnSelectGroup.setText("Group");
        btnSelectGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectGroupActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectGroup);
        btnSelectGroup.setBounds(400, 50, 100, 40);

        cbExam.setFont(new java.awt.Font("Tahoma", 0, 10));
        getContentPane().add(cbExam);
        cbExam.setBounds(70, 160, 320, 20);

        btnSelectSubject.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnSelectSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hd-search-icon.png"))); // NOI18N
        btnSelectSubject.setText("Sub");
        btnSelectSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectSubjectActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectSubject);
        btnSelectSubject.setBounds(400, 100, 100, 40);

        cbSubject.setFont(new java.awt.Font("Tahoma", 0, 10));
        getContentPane().add(cbSubject);
        cbSubject.setBounds(70, 110, 320, 20);

        lblStudentID1.setText("Student ID:");
        lblStudentID1.setMaximumSize(new java.awt.Dimension(30, 50));
        lblStudentID1.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblStudentID1);
        lblStudentID1.setBounds(10, 310, 80, 20);

        lblStudentID2.setText("Group:");
        lblStudentID2.setMaximumSize(new java.awt.Dimension(30, 50));
        lblStudentID2.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblStudentID2);
        lblStudentID2.setBounds(10, 60, 60, 20);

        lblStudentID3.setText("Subject:");
        lblStudentID3.setMaximumSize(new java.awt.Dimension(30, 50));
        lblStudentID3.setMinimumSize(new java.awt.Dimension(30, 50));
        getContentPane().add(lblStudentID3);
        lblStudentID3.setBounds(10, 110, 60, 20);

        btnSelectExam.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnSelectExam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hd-search-icon.png"))); // NOI18N
        btnSelectExam.setText("Exam");
        btnSelectExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectExamActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectExam);
        btnSelectExam.setBounds(400, 150, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // getting all groups

        groupList = newConnection.getGroupList(STARTME.TESTING);
        for (int i=0; i < groupList.size(); i++){

         cbGroup.addItem(""+groupList.get(i).getCourseName()+" "+groupList.get(i).getYear());
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // updates the exam result field
        if (!(txtExamResult.getText().isEmpty())){
            examResult.setExamResult(txtExamResult.getText());
            
            newConnection.saveExamResult(examResult, STARTME.TESTING);
            
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        
            // closes form
                this.setVisible(false);
                eraseInfo(true,true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void lstPersonsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPersonsValueChanged
        // updates the information about exam
        if (!(lstPersons.isSelectionEmpty())){
            examResult = newConnection.getExamResult(studentList.get(lstPersons.getSelectedIndex()),
                    examList.get(cbExam.getSelectedIndex()), STARTME.TESTING);


            txtStudentID.setText(""+examResult.getStudentID());
            txtExamID.setText(""+examResult.getExamID());
            txtExamResult.setText(""+examResult.getExamResult());

            if (examResult.getExamResult()>0){
                txtExamResult.setEnabled(true);
            } else {
                txtExamResult.setEnabled(false);
            }
        }



    }//GEN-LAST:event_lstPersonsValueChanged

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        //disable several buttons and selections
        if (!txtExamResult.isEnabled()){
        eraseInfo(false,false);
        btnSave.setEnabled(false);
        btnClose.setEnabled(false);
        lstPersons.setEnabled(false);
        btnSaveNew.setVisible(true);
        btnNew.setVisible(false);
        txtExamResult.setEnabled(true);
        }


    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNewActionPerformed
        //insert new exam result into table
        if (!(txtExamResult.getText().isEmpty())){
            examResult.setExamID(""+examList.get(cbExam.getSelectedIndex()).getExamID());
            examResult.setStudentID(""+studentList.get(lstPersons.getSelectedIndex()).getbdId());
            examResult.setExamResult(txtExamResult.getText());

            newConnection.insertNewExamResult(examResult, STARTME.TESTING);

            txtStudentID.setText(""+studentList.get(lstPersons.getSelectedIndex()).getbdId());
            txtExamID.setText(""+examList.get(cbExam.getSelectedIndex()).getExamID());

            btnSave.setEnabled(true);
            btnClose.setEnabled(true);
            lstPersons.setEnabled(true);
            btnSaveNew.setVisible(false);
            btnNew.setVisible(true);
            
        }
       
    }//GEN-LAST:event_btnSaveNewActionPerformed

    private void btnSelectGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectGroupActionPerformed
        // getting all subjects and subject assignments
        //groupList.get(cbGroup.getSelectedIndex()).getGroupID(); // retuns the id of selected group
        eraseInfo(false,true);

        studentList =  newConnection.getStudentsInGroup(groupList.get(cbGroup.getSelectedIndex()).getGroupID(), STARTME.TESTING);

        for (int i=0; i < studentList.size(); i++){

         lstBox.addElement(studentList.get(i).getFirstName() + " " + studentList.get(i).getLastName());
        }

        cbSubject.removeAllItems();
        subjectList = newConnection.getSubjectListFromGTS(groupList.get(cbGroup.getSelectedIndex()), null, STARTME.TESTING);

        for (int i=0; i < subjectList.size(); i++){
            cbSubject.addItem("" + subjectList.get(i).getSubjectName());
        }

        lstPersons.setEnabled(false);
        btnNew.setEnabled(false);
        btnSave.setEnabled(false);
        cbExam.removeAllItems();
    }//GEN-LAST:event_btnSelectGroupActionPerformed

    private void btnSelectSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectSubjectActionPerformed
        // getting all information about assingments
        cbExam.removeAllItems();
        examList = newConnection.getExamList(subjectList.get(cbSubject.getSelectedIndex()), STARTME.TESTING);

        for (int i=0; i < examList.size(); i++){
            cbExam.addItem("" + examList.get(i).getExamName());
        }

        if (cbExam.getItemCount()>0){
        lstPersons.setEnabled(true);
        btnNew.setEnabled(true);
        btnSave.setEnabled(true);
        } else {
            lstPersons.setEnabled(false);
            btnNew.setEnabled(false);
            btnSave.setEnabled(false);}
    }//GEN-LAST:event_btnSelectSubjectActionPerformed

    private void txtExamResultKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExamResultKeyTyped
        // validation
        datavalidation.percentValidation(evt, txtExamResult);
    }//GEN-LAST:event_txtExamResultKeyTyped

    private void txtExamResultKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExamResultKeyReleased
        // autocorrection
        autocorrection.percentCorrection(txtExamResult);
    }//GEN-LAST:event_txtExamResultKeyReleased

    private void btnSelectExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectExamActionPerformed
        // TODO add your handling code here:
        String res ="";

       for (int i=0; i < studentList.size(); i++){
           examResult = newConnection.getExamResult(studentList.get(i),
                    examList.get(cbExam.getSelectedIndex()), STARTME.TESTING);

                    

            if (examResult.getExamResult()>0){
               res = "\t\t\t"+examResult.getExamResult() +" %";
            } else {
                res ="";
            }


            lstBox.setElementAt( res +"   " + studentList.get(i).getFirstName()
                    + " " + studentList.get(i).getLastName(), i);


         //lstBox.addElement(studentList.get(i).getFirstName() + " " + studentList.get(i).getLastName());
        }
    }//GEN-LAST:event_btnSelectExamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveNew;
    private javax.swing.JButton btnSelectExam;
    private javax.swing.JButton btnSelectGroup;
    private javax.swing.JButton btnSelectSubject;
    private javax.swing.JComboBox cbExam;
    private javax.swing.JComboBox cbGroup;
    private javax.swing.JComboBox cbSubject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExamID;
    private javax.swing.JLabel lblExamResult;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblStudentID1;
    private javax.swing.JLabel lblStudentID2;
    private javax.swing.JLabel lblStudentID3;
    private javax.swing.JList lstPersons;
    private javax.swing.JTextField txtExamID;
    private javax.swing.JTextField txtExamResult;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables

}
