/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserMenu.java
 *
 * Created on 28-Feb-2013, 14:56:07
 */

package forms;

/**
 *
 * @author Evilguy
 */
public class UserMenu extends javax.swing.JInternalFrame {

    /** Creates new form UserMenu */
    public UserMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPersonalDetails = new javax.swing.JButton();
        btnStudentResults = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMinimumSize(new java.awt.Dimension(280, 440));
        setPreferredSize(new java.awt.Dimension(280, 440));
        getContentPane().setLayout(null);

        btnPersonalDetails.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnPersonalDetails.setText("Personal Details");
        btnPersonalDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnPersonalDetails);
        btnPersonalDetails.setBounds(10, 10, 200, 30);

        btnStudentResults.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnStudentResults.setText("Student Results");
        btnStudentResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentResultsActionPerformed(evt);
            }
        });
        getContentPane().add(btnStudentResults);
        btnStudentResults.setBounds(10, 50, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        //closes all forms
        private void closeForms(){
        if (STARTME.PD.isVisible()){STARTME.PD.setVisible(false);}
        if (STARTME.SRFT.isVisible()){STARTME.SRFT.setVisible(false);}
        }

    private void btnPersonalDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalDetailsActionPerformed
        // Run Personal Details form
        closeForms();
        STARTME.PD.setVisible(true);
        
        
}//GEN-LAST:event_btnPersonalDetailsActionPerformed

    private void btnStudentResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentResultsActionPerformed
        // Run Student Results form
        closeForms();
        STARTME.SRFT.setVisible(true);
    }//GEN-LAST:event_btnStudentResultsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPersonalDetails;
    private javax.swing.JButton btnStudentResults;
    // End of variables declaration//GEN-END:variables

}
